version: '3.8'
services:
 web:
    build: ./app
    ports:
      - "5001:5001"
    depends_on:
      - db
 db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employees
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
