version: '3.8'
services:
  web:
    build: ./app
    ports:
      - "5001:5001"
    volumes:
      - ./app:/app  # Mounts the code into the container, enabling live updates
    depends_on:
      - db
    environment:
      - FLASK_ENV=development  # Set Flask environment to development to enable debug mode
      - DEBUG=True  # Make sure this is set to True

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employees
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
